= CareerSignal API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== 1. 유저 API
=== 1.1. 관리자 여부 확인
operation::user/am-i-admin[snippets='http-request,http-response']

=== 1.2. 유저 등록 (관리자)
operation::user/signup[snippets='http-request,request-fields,http-response,response-fields']

=== 1.3. 유저 전체 조회 (관리자)
operation::user/show-users[snippets='http-request,http-response,response-fields']

=== 1.4. 유저 삭제 (관리자)
operation::user/delete-user[snippets='http-request,path-parameters,http-response']

=== 1.5. 로그인
operation::user/login[snippets='http-request,request-fields,http-response,response-fields']

=== 1.6. 로그아웃
operation::user/logout[snippets='http-request,http-response']

=== 1.7. CSV로 유저 일괄 등록 (관리자)
operation::user/create-users-byCSV[snippets='http-request,request-parts,http-response']


== 2. 멘토 API

=== 2.1. 멘토 전체 조회
operation::mentor/show-mentors[snippets='http-request,http-response,response-fields']

=== 2.2. 멘토 필터링 검색
operation::mentor/search-mentors[snippets='http-request,query-parameters,http-response,response-fields']

=== 2.3. 멘토 등록 (관리자)
operation::mentor/create-mentor[snippets='http-request,request-fields,http-response,response-fields']

=== 2.4. 멘토 수정 (관리자)
operation::mentor/update-mentor[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 2.5. 멘토 삭제 (관리자)
operation::mentor/delete-mentor[snippets='http-request,path-parameters,http-response']

=== 2.6. CSV로 멘토 일괄 등록 (관리자)
operation::mentor/create-mentors-byCSV[snippets='http-request,request-parts,http-response']


== 3. 투표 및 관심 등록 API

=== 3.1. 투표 목록 조회
operation::vote/show-votes[snippets='http-request,http-response,response-fields']

=== 3.2. 투표 생성
operation::vote/create-vote[snippets='http-request,request-fields,http-response,response-fields']

=== 3.3. 관심 등록 (즐겨찾기)
operation::vote/create-favorite[snippets='http-request,request-fields,http-response,response-fields']

=== 3.4. 투표 취소 (삭제)
operation::vote/delete-vote[snippets='http-request,path-parameters,http-response']

=== 3.5. 특정 멘토 투표 수 조회
operation::vote/get-mentor-vote-count[snippets='http-request,path-parameters,http-response']

=== 3.6. 잔여 투표권 수 조회
operation::vote/get-remaining-vote-count[snippets='http-request,http-response']


== 4. 파일 (File) API

=== 4.1. 파일 업로드
operation::file/upload-file[snippets='http-request,request-parts,http-response']

=== 4.2. 파일 조회 및 다운로드
operation::file/view-file[snippets='http-request,path-parameters,http-response']